name: Update personal readme
on: 
    push:
    schedule:
        - cron: '0 */4 * * *'
    workflow_dispatch:

jobs: 
    update-readme:
        name: update latest post and github summary
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps: 
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "5"
                feed_list: "https://blog.cong.moe/index.xml"
            - uses: vn7n24fzkq/github-profile-summary-cards@release
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
              with:
                USERNAME: ${{ github.repository_owner }}
            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk@v3
              with:
                github_user_name: ${{ github.repository_owner }}
                outputs: |
                    profile-summary-card-output/github-contribution-grid-snake.svg
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Get last commit message
              id: last-commit-message
              run: |
                echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: ${{ steps.last-commit-message.outputs.msg }}
                commit_options: '--amend --no-edit --allow-empty'
                push_options: '--force'
                skip_fetch: true
                # Optional commit user and author settings
                commit_user_name: profile-summary-cards[bot]
                commit_user_email: profile-summary-cards-bot@example.com
                commit_author: profile-summary-cards[bot] <profile-summary-cards-bot@example.com>
